<a href="https://colab.research.google.com/github/VictorHFr/Taller_de_Herramientas_Computacionales/blob/main/TareaE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Bibliografia](https://www.youtube.com/watch?v=Rlo9M4dAPTg)
#TareaE
#Victor Manuel Hernández Franco
#Nombre del programa: Funciones de matrices

In [1]:
#toda la tarea de matrices la voy a realizar con numpy ya que asi el codigo se vuelve mas facil de leer y hacer
#1. Sumas de matrices rectangulares.
import numpy as np

# Ejemplo de matrices, son las matrices que voy a ocupar para toda la tarea para no tener que escribir nuevas en cada programa
matriz1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matriz2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

# Realizar la suma de las matrices
resultado = matriz1 + matriz2

# Mostrar el resultado
print("Resultado de la suma:")
print(resultado)


Resultado de la suma:
[[ 8 10 12]
 [14 16 18]]


In [3]:
#2. Multiplicación entrada a entrada rectangulares.
import numpy as np

# Realizar la multiplicación entrada a entrada de las matrices
resultado = matriz1 * matriz2

# Mostrar el resultado
print("Resultado de la multiplicación entrada a entrada:")
print(resultado)

Resultado de la multiplicación entrada a entrada:
[[ 7 16 27]
 [40 55 72]]


In [4]:
#3.la traza de una matariz
import numpy as np

# aqui si uso otra matriz ya que la traza se realiza solo con una
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Calcular la traza de la matriz
traza = np.trace(matriz)

# Mostrar la traza
print("Matriz:")
print(matriz)
print("Traza de la matriz:", traza)

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Traza de la matriz: 15


In [5]:
#4. La transpuesta.
import numpy as np


# Calcular la transpuesta de la matriz usando numpy.transpose()
#La función numpy.transpose() en NumPy se utiliza para calcular la transpuesta de una matriz.
transpuesta = np.transpose(matriz)

# Mostrar la matriz original y su transpuesta
print(matriz)
print("Matriz transpuesta:")
print(transpuesta)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz transpuesta:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
#5. El máximo y mínimo elemento en una matriz.
import numpy as np

# Encontrar el valor máximo en la matriz
maximo = np.max(matriz)

# Encontrar el valor mínimo en la matriz
minimo = np.min(matriz)

# Mostrar los resultados
print("Matriz:")
print(matriz)
print("Valor máximo:", maximo)
print("Valor mínimo:", minimo)


Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Valor máximo: 9
Valor mínimo: 1


In [7]:
#6. La suma del cuadrado de los elementos de una matriz.
import numpy as np

# Elevar al cuadrado cada elemento de la matriz
matriz_cuadrada = np.square(matriz)

# Calcular la suma de los cuadrados de los elementos
suma_cuadrados = np.sum(matriz_cuadrada)

# Mostrar los resultados
print("Matriz original:")
print(matriz)
print("Matriz elevada al cuadrado:")
print(matriz_cuadrada)
print("Suma de los cuadrados de los elementos:", suma_cuadrados)


Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz elevada al cuadrado:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Suma de los cuadrados de los elementos: 285


In [8]:
#7. La potencia de matrices.
import numpy as np

# Elevar la matriz a la potencia 3
potencia = 3

matriz_potenciada = np.linalg.matrix_power(matriz, potencia)

# Mostrar el resultado
print("Matriz original:")
print(matriz)
print(f"Matriz elevada a la potencia {potencia}:")
print(matriz_potenciada)


Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz elevada a la potencia 3:
[[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]
